import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
    await page.goto('http://uitestingplayground.com/');
});

// TC1 - To Verify CodeGen doesn't use Dynamic ID for catch element.
test('Dynamic ID', async ({ page }) => {
    await page.getByText('Dynamic ID', { exact: true }).click();
    expect(page.url()).toEqual('http://uitestingplayground.com/dynamicid');

    // Generated by codegen. 
    await page.getByRole('button', { name: 'Button with Dynamic ID' }).click();
});