import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
    await page.goto('http://uitestingplayground.com/');
});

// TC1 - To Verify CodeGen doesn't use Dynamic ID for catch element.
test('Dynamic ID', async ({ page }) => {
    await page.getByText('Dynamic ID', { exact: true }).click();
    expect(page.url()).toEqual('http://uitestingplayground.com/dynamicid');

    // Generated by codegen. 
    await page.getByRole('button', { name: 'Button with Dynamic ID' }).click();

    // Result: CodeGen catch correct locator.
});

// TC2 - How to locate element when Class attribute of an element may contain more than one class reference
test("class attribute", async ({ page, context }) => {
    await page.getByText('Class Attribute', { exact: true }).click();
    await page.locator('[class="btn class2 btn-primary btn-test"]').click();
    expect(page.url()).toEqual('http://uitestingplayground.com/classattr');

    // Result: We can use playwright locator which is support full class value.
});